linters:

  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: false

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    allow_non_nested_indentation: true
    character: space
    width: 2

  LeadingZero:
    enabled: true
    style: include_zero

  MergeableSelector:
    enabled: false
    force_nesting: false

  NameFormat:
    enabled: true
    convention: hyphenated_lowercase
    allow_leading_underscore: true

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertyCount:
    enabled: false

  PropertySortOrder:
    enabled: true
    order:
      # Generated Content
      - content

      - counter-increment
      - counter-reset

      - list-style
      - list-style-image
      - list-style-position
      - list-style-type

      - quotes

      # Flow Context
      - display
      - overflow
      - visibility

      # Position Model
      - clip
      - position
      - z-index

      - top
      - right
      - bottom
      - left

      # Float Model
      - clear
      - float

      # Flex Model
      - flex
      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap

      - align-content
      - align-items
      - align-self
      - justify-content
      - order

      # Grid Model
      - grid

      # Box Model
      - box-sizing

      - width
      - max-width
      - min-width

      - height
      - max-height
      - min-height

      - box-decoration-break

      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left

      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-collapse
      - border-color
      - border-radius
      - border-spacing
      - border-style
      - border-width

      # Visual Box
      - background
      - background-size
      - box-shadow
      - object-fit
      - opacity

      - outline
      - outline-color
      - outline-style
      - outline-width

      # Typography
      - color

      - font-family
      - font-size
      - font-stretch
      - font-style
      - font-variant
      - font-weight

      - hanging-punctuation

      - letter-spacing
      - line-height

      - text-align
      - text-decoration
      - text-indent
      - text-justify
      - text-overflow
      - text-shadow
      - text-stroke
      - text-transform

      - vertical-align

      - white-space
      - word-break
      - word-spacing

      # Animation
      - animation
      - animation-delay
      - animation-direction
      - animation-duration
      - animation-iteration-count
      - animation-fill-mode
      - animation-name
      - animation-play-state
      - animation-timing-function

      # Transform
      - backface-visiblity

      - perspective
      - perspective-origin

      - transform
      - transform-origin
      - transform-style

      # Transition
      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function

      # Will Change
      - will-change

      # Pointer and Selection
      - appearance
      - cursor
      - pointer-events
      - user-select

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: false

  PseudoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_lowercase

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: at_least_one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    style: space
    allow_single_line_padding: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: false

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false

  VendorPrefixes:
    enabled: true
    identifier_list: base
    include: []
    exclude: []

  ZeroUnit:
    enabled: true
